repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.7.4
    hooks:
      # Sort imports.
      - id: ruff
        args: ["check", "--select", "I", "--fix"]
        types: [python]
        stages: [pre-commit]
      # Run the linter.
      - id: ruff
        args: [--fix]
        stages: [pre-commit]
      # Run the formatter.
      - id: ruff-format
        stages: [pre-commit]
